### ISSUE TITLE
How do you configure rules?

### ISSUE THREAD

**Issue by Timmmm** [denoland/deno_lint#699] opened 2021-05-16 09:31 UTC
Might be obvious but I can't see it mentioned anywhere in the readme or in the Deno docs how you actually choose which rules are enabled.

**Comment by magurotuna** [comment] 2021-05-16 10:51
Currently, there's no way to configure which rules are enabled. deno_lint is designed to be as opinionated as possible - having no config file, which leads to a circumstance where all people are following the same lint rules, would be great for the entire Deno ecosystem.
That being said, we're aware that there are not a few people who want a config file. We have a issue about it (https://github.com/denoland/deno_lint/issues/166) but haven't got a consensus yet.

**Comment by Timmmm** [comment] 2021-05-16 10:56
I wondered if that might be the case. I doubt it is achievable to be honest due to the number of mad old JavaScript features people are going to want to use, and just differing opinions, but it is a commendable goal.

So how come on lint.deno.land some rules are "Recommended" and others aren't?

**Comment by magurotuna** [comment] 2021-05-16 11:07
Recommended rules are just brought from [ESLint](https://eslint.org/docs/rules/) and [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/blob/cae4f4a0f33f8c954b1670d0abcfc8edd6193a06/packages/eslint-plugin/src/configs/eslint-recommended.ts). These recommended rules are widely accepted among JS/TS community.
In deno_lint, to be honest, the rules that are not in "recommended" set are less maintained, so they likely have lots of false positives/negatives.

**Comment by Timmmm** [comment] 2021-05-16 16:21
Right, but what's the point of marking some as recommend and not others if they are all enabled and there's no way to change that?

**Comment by lucacasonato** [comment] 2021-05-16 16:22
Only recommended rules are enabled. The other rules are currently not available. We might provide a configuration for enabling these later down the line.

**Comment by Timmmm** [comment] 2021-05-16 19:59
Ah ok. Might be worth clarifying that for now at least.

**Comment by kitsonk** [comment] 2021-05-16 23:25
Duplicate of #166

**Closed by kitsonk** 2021-05-16 23:25 UTC
