### ISSUE TITLE
 [dynamic import] import is not defined

### ISSUE THREAD

**Issue by ynwd** [denoland/deno_lint#339] opened 2020-09-27 05:30 UTC
Typescript:
```ts
const service = await import(fileImport);
```

Error:
```
(no-undef) import is not defined
          const service = await import(fileImport);
                                ^^^^^^
    at /home/x230/me/app/server.ts:60:32
```

**Comment by kitsonk** [comment] 2020-09-27 07:24
Duplicate of #321

**Closed by kitsonk** 2020-09-27 07:24 UTC

**Comment by ynwd** [comment] 2020-09-27 10:16
@kitsonk what is the solution of this error?

**Comment by lucacasonato** [comment] 2020-09-27 10:17
Fix will land in Deno 1.4.3
